name: ./run.sh

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - stable

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: ./run.sh 100
        run: ./run.sh 100
